In [68]:
import numpy as np

In [69]:
my_arr = np.array([[1,2,3,4],[5,6,7,8]])


In [70]:
my_arr[1,1]

6

In [71]:
my_arr.shape

(2, 4)

In [72]:
my_arr.dtype

dtype('int64')

In [73]:
my_arr[0,2] = 45

In [74]:
my_arr

array([[ 1,  2, 45,  4],
       [ 5,  6,  7,  8]])

# array creation : (1) Conversion from other Python structures (i.e. lists and tuples)

In [75]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [76]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
listarray.dtype

dtype('int64')

In [78]:
listarray.shape

(3, 3)

In [79]:
listarray.size

9

# (2) Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [80]:
zeros = np.zeros((2,5))

In [81]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
zeros.shape

(2, 5)

In [83]:
zeros.size

10

In [84]:
zeros.dtype

dtype('float64')

In [85]:
rng = np.arange(15)

In [86]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [87]:
rng.dtype

dtype('int64')

In [88]:
rng.shape

(15,)

In [89]:
rng.size

15

In [90]:
lspace = np.linspace(1,5,12)

In [91]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [92]:
emp = np.empty((4,6))

In [93]:
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [94]:
emp_like = np.empty_like(lspace)

In [95]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [96]:
ide = np.identity(20)

In [97]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [98]:
ide.shape

(20, 20)

In [99]:
ide.size

400

In [100]:
arr = np.arange(99)

In [101]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [102]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [103]:
# np.eye(n, m) defines a 2D identity matrix. The elements where i=j (row index
# and column index are equal) are 1 and the rest are 0, as such:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [104]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [105]:
# numpy.diag can define either a square 2D array with given values along the
# diagonal or if given a 2D array returns a 1D array that is only the diagonal
# elements. The two array creation functions can be helpful while doing linear
# algebra, as such:

np.diag([1, 2, 3])


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [106]:
np.diag([1, 2, 3], 1)


array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [107]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

In [108]:
# vander(x, n) defines a Vandermonde matrix as a 2D NumPy array. Each column of
# the Vandermonde matrix is a decreasing power of the input 1D array or list or
# tuple, x where the highest polynomial order is n-1. This array creation
# routine is helpful in generating linear least squares models, as such:
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [109]:
np.vander([1, 2, 3, 4], 2)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [110]:
np.vander((1, 2, 3, 4), 4)


array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

# (3) Replicating, joining, or mutating existing arrays

In [111]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In [112]:
# if we create a two different array then b not collaps with a
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


In [113]:
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
np.block([[A, B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

# work with the axis in numpy

In [114]:
x = [[1,2,3],[4,5,6],[7,1,8]]

In [115]:
ar = np.array(x)

In [116]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 8]])

In [117]:
ar.sum(axis=0)

array([12,  8, 17])

In [118]:
ar.sum(axis=1)

array([ 6, 15, 16])

In [119]:
# how to transpose the array
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 8]])

In [122]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
1
8


In [123]:
ar.ndim

2

In [124]:
ar.size

9

In [125]:
ar.nbytes

72

In [126]:
one = np.array([1,2,3,4,5,6])

In [127]:
one.argmax()

5

In [128]:
one.argmin()

0

In [129]:
one.argsort()

array([0, 1, 2, 3, 4, 5])

In [130]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 8]])

In [132]:
ar.argmax()

8

In [133]:
ar.argmin()

0

In [134]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [1, 0, 2]])

In [135]:
ar.argmax(axis=1)

array([2, 2, 2])

In [136]:
ar.argmin(axis=0)

array([0, 2, 0])

In [138]:
ar.argsort(axis=0)

array([[0, 2, 0],
       [1, 0, 1],
       [2, 1, 2]])

In [139]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [1, 0, 2]])

In [140]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 8])

In [141]:
ar.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 8]])

In [142]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 8]])

In [144]:
ar2 = np.array([[1, 5, 3],
       [4, 2, 6],
       [7, 0, 8]])
ar2

array([[1, 5, 3],
       [4, 2, 6],
       [7, 0, 8]])

In [145]:
ar + ar2

array([[ 2,  7,  6],
       [ 8,  7, 12],
       [14,  1, 16]])

In [146]:
ar * ar2

array([[ 1, 10,  9],
       [16, 10, 36],
       [49,  0, 64]])

In [147]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 2.82842712]])

In [148]:
np.sqrt(ar2)

array([[1.        , 2.23606798, 1.73205081],
       [2.        , 1.41421356, 2.44948974],
       [2.64575131, 0.        , 2.82842712]])

In [150]:
ar.sum()

37

In [152]:
ar.max()

8

In [153]:
ar.min()

1

In [155]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 8]])

In [157]:
np.where(ar>5)

(array([1, 2, 2]), array([2, 0, 2]))

In [158]:
type(np.where(ar>5))

tuple

In [159]:
np.count_nonzero(ar)

9

In [161]:
import sys

In [160]:
py_ar = [1,2,3,4]
np_ar = np.array(py_ar)

In [162]:
sys.getsizeof(1)*len(py_ar)

112

In [165]:
np_ar.itemsize * np_ar.size

32